// Auto-generated from 07_streaming.ipynb
// Do not edit manually -- regenerate with nb2typ.py
#import "../../template.typ": *
#import "../../metadata.typ": *

#chapter(7, "streaming", subtitle: "Observe agent execution in real time")

== Learning Objectives

Understand and utilize the various streaming modes of LangGraph.

- Understand the differences between `values`, `updates`, `messages`, `custom`, `debug` modes
- Identify appropriate use cases for each streaming mode
- Learn how to use multiple streaming modes simultaneously

== 7.1 Environment Setup

== 7.2 streaming Mode Comparison

LangGraph provides various streaming modes. Each mode conveys a different level of information in real time.

#table(
  columns: 3,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[mode],
  text(weight: "bold")[Description],
  text(weight: "bold")[Use],
  [`values`],
  [Total state of each step],
  [Debugging, tracing state],
  [`updates`],
  [Only updates returned by each node],
  [Show progress],
  [`messages`],
  [Message Token Unit],
  [Chat UI],
  [`custom`],
  [custom event],
  [Custom Progress],
  [`debug`],
  [Full debug information],
  [Debugging during development],
)

== 7.3 stream_mode="values" — Full state snapshot

`values` mode returns _full state_ after each node execution. This is useful for tracking the overall flow of how the graph progresses.

== 7.4 stream_mode="updates" — Node-specific updates

`updates` mode only passes the update value returned by each node. You can see exactly which nodes made which changes.

== 7.5 stream_mode="messages" — Per-token streaming

The `messages` mode delivers _tokens generated by LLM in real time_. Best suited for implementing typing effects in chat UI.

== 7.6 Simultaneous use of multiple streaming modes

You can use multiple modes _simultaneously_ by passing a list to `stream_mode`. The returned event is in the form of a `(mode, data)` tuple.

== 7.7 stream_mode="custom" — custom streaming

`custom` mode allows you to streaming** arbitrary data directly inside a node.

If you call `get_stream_writer()` of `langgraph.config`, you can get the `writer` function. If you pass data such as a dictionary to this function, it will be sent to the client in real time while the graph is running.

_Use Case:_
- _Progress_ reporting of long tasks
- _Chunk-wise streaming_ in external LLM without using LangChain
- Immediate delivery of _intermediate results_ inside the node

#tip-box[If you graph with `stream_mode="custom"` streaming, only the data sent with `writer()` will be received.]

== 7.8 Summary

#table(
  columns: 3,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[streaming mode],
  text(weight: "bold")[Description],
  text(weight: "bold")[Use],
  [`values`],
  [Return full state after each step],
  [Debugging, tracing state],
  [`updates`],
  [Return only the part changed by the node],
  [Monitor progress],
  [`messages`],
  [LLM token real-time streaming],
  [Chat UI implementation],
  [Multiple modes simultaneously],
  [Pass as list → Receive `(mode, data)` tuple],
  [Complex Monitoring],
  [`custom`],
  [Send random data to `get_stream_writer()`],
  [Progress Reporting, External LLM],
)

=== Next Steps
→ _#link("./08_interrupts_and_time_travel.ipynb")[08_interrupts_and_time_travel.ipynb]_: Learn interrupts and time travel.
